mediaFileServer:
  port: 3000
notificationServer:
  port: 3001
webServer:
  port: 8080
common:
  hostname: 192.168.100.109
  protocol: http
  scanDelayAfterWakeupTimeMillis: 15000
  renewUPnPSubscriptionIntervalMillis: 30000
  getPositionInfoIntervalMillis: 2000
  watchdogIntervalMillis: 10000
  watchdogNoActivityIntervalMillis: 60000
media:
  rawInputFolder: media/raw_folder
  processedInputFolder: media/playback_folder
  vlcExecutable: vlc
scheduler:
  enabled: false
  startTime: 09:00
  endTime: 18:00
  weekDays:
    Mon: false
    Tue: false
    Wed: false
    Thu: false
    Fri: false
    Sat: false
    Sun: false
