export const ACTIVITY = {
    SSDP: 'SSDP',
    UPNP_CALLS: 'UPNP_CALLS',
    NOTIFY_EVENT: 'NOTIFY_EVENT',
    GET_POSITION_INFO: 'GET_POSITION_INFO'
}

export const PLAYBACK_STATE = {
    PLAYING: "PLAYING",
    TRANSITIONING: "TRANSITIONING",
    STOPPED: "STOPPED",
}

export const CONNECTION_STATE = {
    CONNECTING: "CONNECTING",
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    ERROR_STATE: "ERROR_STATE",
    DISABLED: "DISABLED"
}

export const SETTINGS = {
    MAX_GET_POSITION_INFO_ERRORS: 3
}

export const EVENTS = {
    MEDIA_FILES_UPDATE: 'MEDIA_FILES_UPDATE',
    SSPD_SCAN_START: 'SSPD_SCAN_START',
    SSPD_REPLY: 'SSPD_REPLY',
    UPNP_NOTIFICATION: 'UPNP_NOTIFICATION',
    WAKE_UP: 'WAKE_UP',
    SCHEDULER_ON: 'SCHEDULER_ON',
    SCHEDULER_OFF: 'SCHEDULER_OFF'
}