export const ACTIVITY = {
    SSDP: 'SSDP',
    UPNP_CALLS: 'UPNP_CALLS',
    NOTIFY_EVENT: 'NOTIFY_EVENT',
    GET_POSITION_INFO: 'GET_POSITION_INFO'
}

export const PLAYBACK_STATE = {
    PLAYING: "PLAYING",
    TRANSITIONING: "TRANSITIONING",
    STOPPED: "STOPPED",
}

export const CONNECTION_STATE = {
    CONNECTING: "CONNECTING",
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    ERROR_STATE: "ERROR_STATE"
}

export const SETTINGS = {
    MAX_GET_POSITION_INFO_ERRORS: 3
}